// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrXkpKn-bKOx9ejCRUXV0PtG2CFDSSGEc',
    appId: '1:313729187200:web:1d3ec2736e2118fa5c1565',
    messagingSenderId: '313729187200',
    projectId: 'unity-uplift',
    authDomain: 'unity-uplift.firebaseapp.com',
    storageBucket: 'unity-uplift.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjC3aG-7UpA2zF1koQhrUXis_n1N7bV0',
    appId: '1:313729187200:android:ac538beaf7a8bb7c5c1565',
    messagingSenderId: '313729187200',
    projectId: 'unity-uplift',
    storageBucket: 'unity-uplift.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonQqOW2h36KUCe4DmksyKThorIts94wo',
    appId: '1:313729187200:ios:8d2c791abb2f75cf5c1565',
    messagingSenderId: '313729187200',
    projectId: 'unity-uplift',
    storageBucket: 'unity-uplift.appspot.com',
    iosBundleId: 'com.example.unityUplift',
  );
}
